# Version
version: 2.0

# Define Jobs
jobs:
  # Test Docker containers
  build:
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout
      - run: php -v

# Main Config
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
